=== nazimba/Zoogloo-Tools/zRigTools/Application/Plugins/zPoser.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ENTITY version "$Revision: 169 $">
<!ENTITY author "$Author: andy $">
<!ENTITY date "$Date: 2008-04-10 19:11:34 -0700 (Thu, 10 Apr 2008) $">

<!ELEMENT zPoser (object*)>
	<!ATTLIST zPoser name CDATA #REQUIRED>
	<!ATTLIST zPoser author CDATA #IMPLIED>
	<!ATTLIST zPoser date CDATA #IMPLIED>
	<!ATTLIST zPoser version CDATA #IMPLIED>
	<!ATTLIST zPoser image CDATA #IMPLIED>

<!ELEMENT object (channel*)>
	<!ATTLIST object name CDATA #REQUIRED>

<!ELEMENT channel EMPTY>
	<!ATTLIST channel name CDATA #REQUIRED>
	<!ATTLIST channel owner CDATA #REQUIRED>
	<!ATTLIST channel value CDATA #REQUIRED>

=== nazimba/Zoogloo-Tools/zRigTools/Application/Plugins/zPoser.Example.xml
<?xml version="1.0"?>
<!-- 
	Great DTD explanation: 
	http://www.cs.rpi.edu/~puninj/XMLJ/classes/class3/all.html 
	Great Doctype reference:
	http://www.blooberry.com/indexdot/html/tagpages/d/doctype.htm
-->
<!-- <!DOCTYPE zPoser SYSTEM "zPoser.dtd"> -->
<!-- <!DOCTYPE zPoser SYSTEM "http://portal.zoogloo.net/dtds/zPoser.dtd"> -->
<!DOCTYPE zPoser PUBLIC "-//Zoogloo LLC//zPoser//EN" "http://portal.zoogloo.net/dtds/zPoser.dtd">
<zPoser
	name='Fist'
	date='some date'
	image='./reference.jpg'>
	<object  name='fingA1_Lft_Bone' >
		<channel owner='kine.local' name='rotx' value='0'/>
		<channel owner='kine.local' name='roty' value='0'/>
		<channel owner='kine.local' name='rotz' value='0'/>
	</object>
	<object  name='fingA2_Lft_Bone' >
		<channel owner='kine.local' name='rotx' value='0'/>
		<channel owner='kine.local' name='roty' value='0'/>
		<channel owner='kine.local' name='rotz' value='0'/>
	</object>
	<object  name='fingA3_Lft_Bone' >
		<channel owner='kine.local' name='rotx' value='0'/>
		<channel owner='kine.local' name='roty' value='0'/>
		<channel owner='kine.local' name='rotz' value='0'/>
	</object>
</zPoser>
